var barCode = "var svg=d3.select(\"#chart\").append(\"svg:svg\").attr(\"width\",500).attr(\"height\",500);var bar=sap.viz.modules.bar();var prop={animation:{dataLoading:false}};var data={\"sap.viz.modules.bar.series.color\":{key:\"sap.viz.modules.bar.series.color\",values:[{col:{val:\"MND\"},type:\"MND\",rows:[{val:\"Profit\",ctx:{mg:0,mi:0}}]},{col:{val:\"Country\"},rows:[{val:\"China\",ctx:{type:\"Dimension\",path:{aa:1,di:0,dii:0}}},{val:\"China\",ctx:{type:\"Dimension\",path:{aa:1,di:0,dii:1}}},{val:\"USA\",ctx:{type:\"Dimension\",path:{aa:1,di:0,dii:2}}},{val:\"USA\",ctx:{type:\"Dimension\",path:{aa:1,di:0,dii:3}}},{val:\"Canada\",ctx:{type:\"Dimension\",path:{aa:1,di:0,dii:4}}},{val:\"Canada\",ctx:{type:\"Dimension\",path:{aa:1,di:0,dii:5}}}]},{col:{val:\"Year\"},rows:[{val:\"2001\",ctx:{type:\"Dimension\",path:{aa:1,di:1,dii:0}}},{val:\"2002\",ctx:{type:\"Dimension\",path:{aa:1,di:1,dii:1}}},{val:\"2001\",ctx:{type:\"Dimension\",path:{aa:1,di:1,dii:2}}},{val:\"2002\",ctx:{type:\"Dimension\",path:{aa:1,di:1,dii:3}}},{val:\"2001\",ctx:{type:\"Dimension\",path:{aa:1,di:1,dii:4}}},{val:\"2002\",ctx:{type:\"Dimension\",path:{aa:1,di:1,dii:5}}}]}]},\"sap.viz.modules.bar.valueaxis1\":{key:\"sap.viz.modules.bar.valueaxis1\",values:[{col:\"Profit\",rows:[[{val:25,ctx:{type:\"Measure\",path:{mg:0,mi:0,dii_a1:0,dii_a2:0}}},{val:136,ctx:{type:\"Measure\",path:{mg:0,mi:0,dii_a1:1,dii_a2:0}}}],[{val:58,ctx:{type:\"Measure\",path:{mg:0,mi:0,dii_a1:0,dii_a2:1}}},{val:128,ctx:{type:\"Measure\",path:{mg:0,mi:0,dii_a1:1,dii_a2:1}}}],[{val:58,ctx:{type:\"Measure\",path:{mg:0,mi:0,dii_a1:0,dii_a2:2}}},{val:24,ctx:{type:\"Measure\",path:{mg:0,mi:0,dii_a1:1,dii_a2:2}}}],[{val:159,ctx:{type:\"Measure\",path:{mg:0,mi:0,dii_a1:0,dii_a2:3}}},{val:147,ctx:{type:\"Measure\",path:{mg:0,mi:0,dii_a1:1,dii_a2:3}}}],[{val:149,ctx:{type:\"Measure\",path:{mg:0,mi:0,dii_a1:0,dii_a2:4}}},{val:269,ctx:{type:\"Measure\",path:{mg:0,mi:0,dii_a1:1,dii_a2:4}}}],[{val:38,ctx:{type:\"Measure\",path:{mg:0,mi:0,dii_a1:0,dii_a2:5}}},{val:97,ctx:{type:\"Measure\",path:{mg:0,mi:0,dii_a1:1,dii_a2:5}}}]]}]},\"sap.viz.modules.bar.valueaxis2\":{key:\"sap.viz.modules.bar.valueaxis2\",values:[]},\"sap.viz.modules.bar.dimension\":{key:\"sap.viz.modules.bar.dimension\",values:[{col:{val:\"Product\"},rows:[{val:\"Car\",ctx:{type:\"Dimension\",path:{aa:0,di:0,dii:0}}},{val:\"Truck\",ctx:{type:\"Dimension\",path:{aa:0,di:0,dii:1}}}]}]}};bar.width(500);bar.height(300);bar.properties(prop);bar.data(data);svg.data([data]);svg.call(bar);";

var catAxisCode = "var svg=d3.select(\"#chart\").append(\"svg:svg\").attr(\"width\",500).attr(\"height\",500);var axis=sap.viz.modules.axis();var dataset={\"sap.viz.modules.stackedverticalbar.dimension\":{key:\"sap.viz.modules.stackedverticalbar.dimension\",values:[{col:{val:\"Product\"},rows:[{val:\"Car\"},{val:\"Truck\"},{val:\"Truck2\"}]}]}};var axScale=d3.scale.ordinal().domain([0,1,2]).rangeBands([0,389]);axis.data(dataset).scale(axScale).properties({isShowTitle:false,type:\"category\",position:\"left\"});svg.call(axis);";

var valAxisCode = "var svg=d3.select(\"#chart\").append(\"svg:svg\").attr(\"width\",500).attr(\"height\",500);var axis=sap.viz.modules.axis();var axScale=d3.scale.linear().domain([800,0]).range([100,400]);axis.scale(axScale);axis.properties({type:\"value\",position:\"left\",title:{visible:false,text:null},gridline:{visible:true}});axis.gridlineLength(50);svg.call(axis);";

var hcatAxisCode = "var svg=d3.select(\"#chart\").append(\"svg:svg\").attr(\"width\",500).attr(\"height\",500);var axis=sap.viz.modules.axis();var dataset={\"sap.viz.modules.stackedverticalbar.dimension\":{key:\"sap.viz.modules.stackedverticalbar.dimension\",values:[{type:\"MND\",col:{val:\"MND\"},rows:[{val:\"Profit\"},{val:\"Measure\"},{val:\"Measure2\"}]},{col:{val:\"Country\"},rows:[{val:\"China99999999\"},{val:\"China99999999\"},{val:\"USA\"},{val:\"USA\"},{val:\"Canada\"},{val:\"Canada\"}]},{col:{val:\"Year\"},rows:[{val:\"2001\"},{val:\"2002\"},{val:\"2001\"},{val:\"2002\"},{val:\"2001\"},{val:\"2002\"}]}]}};var axScale=d3.scale.ordinal().domain([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]).rangeBands([0,490]);axis.scale(axScale);axis.data(dataset);axis.properties({type:\"category\",position:\"top\",title:{visible:true,text:\"Top Category Axis With MND In The First Level\"}});svg.call(axis);";

var legendCode = "var svg=d3.select(\"#chart\").append(\"svg:svg\").attr(\"width\",500).attr(\"height\",500);var legend=sap.viz.modules.legend();var colorPallet=[\"#00ff00\",\"#338111\",\"#123456\",\"#654321\",\"#564211\",\"#421FFF\"];var shapePallet=[\"triangle-up\",\"circle\",\"square\",\"triangle-down\"];var datas={\"sap.viz.feed.color\":{key:\"sap.viz.feed.color\",values:[{col:{val:\"Country\"},rows:[{val:\"China\"},{val:\"China\"},{val:\"USA\"},{val:\"USA\"},{val:\"Canada\"},{val:\"Canada\"}]},{col:{val:\"Year\"},rows:[{val:\"2001\"},{val:\"2002\"},{val:\"2001\"},{val:\"2002\"},{val:\"2001\"},{val:\"2002\"}]}]}};legend.width(300);legend.height(400);legend.data(datas);legend.shapes(shapePallet);legend.colorPalette(colorPallet);legend.properties({title:{visible:true},isHierarchical:true,position:\"left\"});svg.call(legend);"

var codeList = [];
codeList.push(barCode);
codeList.push(catAxisCode);
codeList.push(hcatAxisCode);
codeList.push(valAxisCode);
codeList.push(legendCode);

